throw unimplemented errors
holo-rea/holo-rea pull request #332
Opened 2022-07-07 03:22 UTC by weswalla

closes #323

2022-07-07 17:39 UTC, Connoropolous commented
Nice. Which ones have we vetted so far between you and me?

2022-07-07 23:29 UTC, weswalla commented
@Connoropolous covered all the ones outlined in #323

2022-07-08 06:23 UTC, Connoropolous requested changes

2022-07-08 06:23 UTC, Connoropolous commented on modules/vf-graphql-holochain/resolvers/agent.ts
> +      proposalsToWithin: async (record: Agent): Promise<ProposalConnection> => {
this one doesn't exist and caused an error during my local test run. remove

2022-07-08 16:00 UTC, Connoropolous commented
@weswalla check out the issue again, I've updated it with what I hope is the full list

2022-07-08 16:23 UTC, Connoropolous commented on modules/vf-graphql-holochain/resolvers/commitment.ts
> +      resourceInventoriedAs: async (record: Commitment): Promise<EconomicResource> => {
this type `Commitment` isn't right I think

2022-07-12 00:01 UTC, Connoropolous approved these changes

2022-07-12 14:25 UTC, merged